### ISSUE TITLE
Deal with Large Files

### ISSUE THREAD

**Issue by LaurensRietveld** [LODLaundry/lodlaundry.github.io#38]
Support very large single files. To avoid having these in memory (for de-duplication and sorting), stream the entire process, write to tmp disk, and sort/uniq it on disk. Will be slow, but at least it'll work.

Some optimizations possible:
- after downloading/extracting, check free disk of ssd. If it fits, store on that disk. Otherwise, use regular HD.
- See http://unix.stackexchange.com/questions/120096/how-to-sort-big-files for more optimizations (e.g. setting the tmp sort dir to the ssd disk)

**Comment by wouterbeek** [comment]
Streamed processing was added for Trig, Turtle, N-Triples, N-Quads, XML/RDF.
Not for RDFa.
Sorting + deduplication on disk still has to be done.

**Comment by wouterbeek** [comment]
Done!
