### ISSUE TITLE
Archives cannot have a datadump property

### ISSUE THREAD

**Issue by LaurensRietveld** [LODLaundry/lodlaundry.github.io#50]
Archives currently have a datadump property (see e.g. http://lodlaundromat.org/describe/?url=http%3A%2F%2Flodlaundromat.org%2Fresource%2F0af4cf76187202f4f3a051b9542f3b46)

That should not be possible: files inside this archive are published as (gzipped cleaned) data dumps, but the archive itself is not

**Comment by wouterbeek** [comment]
Well spotted! Fixed.
