### ISSUE TITLE
Re-clean certain documents 

### ISSUE THREAD

**Issue by LaurensRietveld** [LODLaundry/lodlaundry.github.io#51]
We might need to re-do some of the crawling/cleaning for certain documents. Nothing major, but some documents are flagged as 'cleaned', without warnings and errors, but have no triples and no clean datadump. E.g. http://lodlaundromat.org/resource/6f5d2706070cdd1ee92d2c300a354a30

**Comment by wouterbeek** [comment]
This is part of a more general issue that I should come up with a query that is able to identify (preferably) all and only data documents that need to be recleaned.
