### ISSUE TITLE
DBLP dataset remains pending

### ISSUE THREAD

**Issue by RubenVerborgh** [LODLaundry/lodlaundry.github.io#58]
I tried adding the dataset http://dblp.l3s.de/dblp.rdf.gz today, but it's apparently already there since 23 September. While it has status "pending", it does not show up when I filter for _pending_ datasets.

Could it be that something went wrong during the conversion process?

**Comment by akuckartz** [comment]
Yes, see #70 (which unfortunately was closed although that issue is not yet resolved). See #67 for more info.

**Comment by wouterbeek** [comment]
I hadn't really paid attention to this particular dataset, but it seems to be cleaned now: http://lodlaundromat.org/resource/c78ccfc9f0cf72b7c00ba0391ce33df1
Notice that it contains a lot of duplicates and several errors as well.

The reason why this dataset took a while to clean probably has to do with the general fact that we started a new crawl in February.
