### ISSUE TITLE
Cannot add certain datasets to the laundry basket

### ISSUE THREAD

**Issue by RubenVerborgh** [LODLaundry/lodlaundry.github.io#59]
When addding `http://download.bio2rdf.org/release/3/drugbank/drugbank.nq.gz`, this error occurs:

> Request URL: http://backend.lodlaundromat.org/?url=http%3A%2F%2Fdownload.bio2rdf.org%2Frelease%2F3%2Fdrugbank%2Fdrugbank.nq.gz
> Response: Failed to add http://download.bio2rdf.org/release/3/drugbank/drugbank.nq.gz to the seed list

**Comment by lanthaler** [comment]
I have the same problem with basically every URL I tried

**Comment by LaurensRietveld** [comment]
@RubenVerborgh  @lanthaler : thanks both for the report. It's working again (workaround though, will fix this issue in another issue)
