### ISSUE TITLE
Cannot search for archives in wardrobe

### ISSUE THREAD

**Issue by RubenVerborgh** [LODLaundry/lodlaundry.github.io#62]
When searching for the dataset `http://worldbank.270a.info/data/meta.tar.gz` in the Laundry Basket, it shows up as “cleaned” (26 September 2014 6:52). However, when searching for it in the Wardrobe, it does not show up. No Triple Pattern Fragments interface seems to have been created either.

I suspect there might be more datasets in this case.

**Comment by LaurensRietveld** [comment]
The problem is: this link is an archive. Each file in the archive will end up as a  document in the wardrobe. The archive -itself- won't.
I'll check whether this is something we can easily fix

**Comment by LaurensRietveld** [comment]
I've improved the wardrobe a bit: the archive entries show up in the listing now.
This is still far from ideal though. Ideally, we'd need a tree-like table structure to visualize the wardrobe contents. 
We'd like to avoid going down the route of enhancing the lodlaundromat front-end to that extent though: ideally, we do the heavy lifting and provide the backend. Other people can then create and/or publish their own front-end, using (and linking to) our backend.

**Comment by wouterbeek** [comment]
We can create a plain list where archive entries have greyed out hdt, ldf,
zip buttons. Optionally give them an archive icon.
