### ISSUE TITLE
Protocol for added URLs should be case-insensitive and default to http

### ISSUE THREAD

**Issue by a3nm** [LODLaundry/lodlaundry.github.io#64]
Right now "example.com/foo" and "Http://example.com/foo" do not work in the intended way. Thanks!

**Comment by LaurensRietveld** [comment]
Hi @a3nm, thanks for the report. Schema is now stored case insensitive! 
And I'd like to only store URLs according to the RFC 3987 and RFC 3986 specs, to avoid to many customizations

**Comment by a3nm** [comment]
Hi, thanks for fixing! I'm not sure I get your point about storage though; I'm not suggesting you store URLs as "example.com/foo", I'm just saying that, if the user enters "example.com/foo" and it doesn't parse, it is probably better to try adding "http://" first, before declaring failure; because it is common for users to not write the leading "http://". If the rewritten URL is OK, you should probably just store the rewritten URL. So that's really not much of a customization, it's just a tweak that would need to be applied to input URLs.

**Comment by LaurensRietveld** [comment]
One issue I'm having with this is the following: 
Suppose a user adds `http//example.com/foo`. The URI parser would detect an absent scheme, and add 'http:'. As a result, `http://http//example.com/foo` (a valid URI) would be added to the seed list.

Not sure which is worst though: users having to type the scheme, or the risk of adding faulty URIs

**Comment by a3nm** [comment]
You probably have to deal anyway with the issue of faulty URIs getting
added to the list, because, e.g., of malicious users. I'm guessing that
the real concern is that the user could think that their URI was
correctly added whereas, in fact, it was not.

I guess to mitigate this you should:

- When a URI is rejected and had no scheme, have the error message point
  out that the scheme should be written; ideally provide a "did you
  mean" link to submit directly with "http://" added.
- If you ever add something to the list that differs from the exact user
  input, echo back the URI in the confirmation message as it was added,
  so the user can know what was really done (ideally provide a way to
  undo if the rewritten URI was incorrect)

Probably the ideal solution would be to do the above, and add "http://"
only when: the input is incorrect, the input with added "http://" is
correct, and, e.g., the input does not start with "http",
case-insensitive, or some other such crude heuristic, to work around the
problem that you mentioned.

**Comment by LaurensRietveld** [comment]
Good point! I've added 'did you mean'  feedback as part of the error message
