### ISSUE TITLE
Improve LODLaundromat pipeline

### ISSUE THREAD

**Issue by LaurensRietveld** [LODLaundry/lodlaundry.github.io#67]
- add better hooks for creating VoiD description, HDT files, and issuing LDF updates
- possibly use RSS feed to provide updates on cleaned datasets (up for discussion)

**Comment by wouterbeek** [comment]
@LaurensRietveld I believe this has largely been done now (point 1). Point 2 will not be pursued if I'm correct.

**Comment by LaurensRietveld** [comment]
Ah, your right. This has been taken care of. The  restart of the crawl includes these improvements.

About the RSS feed: we might consider this when there is an actual use-case or request.
