### ISSUE TITLE
"Something went wrong. Is the url correct?"

### ISSUE THREAD

**Issue by akuckartz** [LODLaundry/lodlaundry.github.io#69]
I attempted to submit http://offenedaten-koeln.de/node/1056.rdf using the form on the page http://lodlaundromat.org/basket/ but got this message:
> Something went wrong. Is the url correct? If this problem persists, please drop us a Github issue!

**Comment by LaurensRietveld** [comment]
Thanks for the report! Fixed.

Cause: some nginx configuration changes responsible for proxying requests between servers resulted in some http headers (such as CORS-related ones) appearing -twice- in responses (something which most browsers do not like)
