### ISSUE TITLE
Metadata in the 'basket graph' cannot be queried

### ISSUE THREAD

**Issue by wouterbeek** [LODLaundry/lodlaundry.github.io#91]
For instance `<IRI, llo:url, URL>` cannot be queried.

**Comment by LaurensRietveld** [comment]
No sure I get the query you'd like to execute. Is it this? (works for me)
```xml
PREFIX llo: <http://lodlaundromat.org/ontology/>
PREFIX ll: <http://lodlaundromat.org/resource/>

SELECT DISTINCT * WHERE {
	<http://lodlaundromat.org/resource/dcefd287bd0c7d4efb543c7260b6dcf8> llo:url ?url
} LIMIT 10
```

**Comment by wouterbeek** [comment]
Indeed, but `llo:url` does not occur in the result set of the following query:

```sparql
PREFIX ll: <http://lodlaundromat.org/resource/>
SELECT DISTINCT ?p ?o
WHERE {
	ll:dec2da62a50549b4f02f85481b0a3a32 ?p ?o .
}
ORDER BY ASC(?p)
LIMIT 100
```

**Comment by LaurensRietveld** [comment]
this one doesnt have a URL as its an archive entry. It's parent (
http://lodlaundromat.org/resource/fcc4e227b43886a3bd9d090e2863df2b) does ;)

**Comment by wouterbeek** [comment]
Yep, I'm going to tag this question with "Wouter-is-an-idiot"!
