### ISSUE TITLE
Dead link?

### ISSUE THREAD

**Issue by wouterbeek** [LODLaundry/lodlaundry.github.io#94]
Came across the following link while running a large-scale experiment (data document number 535,139):

[http://download.lodlaundromat.org/a208fc1ca0bc01e26f94f802c0e67d1d](http://download.lodlaundromat.org/a208fc1ca0bc01e26f94f802c0e67d1d)

**Comment by LaurensRietveld** [comment]
I'd guess that this is a one-time glitch. This file has a corrupt gzip file. Could you reset it?

**Comment by wouterbeek** [comment]
Indeed! Resetting this one fixed the problem.
